2024-06-15 14:23:45 [MappingExecutionBatch] Apex Class [Mapping_Vehicle_Asset] threw an unhandled exception: System.QueryException: Record Currently Unavailable: The record you are attempting to edit or one of its related records is currently being modified by another user
2024-06-16 09:12:30 [Mapping_Vehicle_Asset] 16 of 16 records failed to save.[Mapping_Vehicle_Asset] Failed to save record [ID=null Message=INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST:Exterior Finish: bad value for restricted picklist field: EXT09 Exterior_Finish__c=EXT09][Mappi
2024-06-17 11:45:12 [Mapping_Vehicle_Asset] Failed to save record [ID=02i1Q000008dc4VQAQ Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:AssetTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.CreateTasksAndCasesOnDeliveryForEU.createTasksOnDeliveryFromAsset: line 202 column 1 Class.AssetTriggerHandler.createTasksOnDeliveryForEU: line 393 column 1 Class.AssetTriggerHandler.afterUpdate: line 109 column 1 Trigger.AssetTrigger: line 24 column 1 ]
2024-06-18 08:34:56 [Mapping_Vehicle_Asset] Failed to save record [ID=02i1Q000008dcsHQAQ Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:AssetTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.CreateTasksAndC
2024-06-19 15:22:43 [Mapping_Vehicle_Asset] Failed to save record [ID=02i1Q000008dnovQAA Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:AssetTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.CreateTasksAndC
2024-06-20 10:11:29 [Mapping_Vehicle_Asset] Failed to save record [ID=02i1Q000008dnn2QAA Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:AssetTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.CreateTasksAndCasesOnDeliveryForEU.createTasksOnDeliveryFromAsset: line 202 column 1 Class.AssetTriggerHandler.createTasksOnDeliveryForEU: line 393 column 1 Class.AssetTriggerHandler.afterUpdate: line 109 column 1 Trigger.AssetTrigger: line 24 column 1 ]
2024-06-21 13:55:17 [Mapping_Vehicle_Asset] Failed to save record [ID=02i1Q000008dnnlQAA Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:AssetTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.CreateTasksAndCasesOnDeliveryForEU.createTasksOnDeliveryFromAsset: line 202 column 1 Class.AssetTriggerHandler.createTasksOnDeliveryForEU: line 393 column 1 Class.AssetTriggerHandler.afterUpdate: line 109 column 1 Trigger.AssetTrigger: line 24 column 1 ]
2024-06-22 07:44:02 [Mapping_Vehicle_Asset] Failed to save record [ID=02i1Q000008dnoxQAA Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:AssetTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.CreateTasksAndCasesOnDeliveryForEU.createTasksOnDeliveryFromAsset: line 202 column 1 Class.AssetTriggerHandler.createTasksOnDeliveryForEU: line 393 column 1 Class.AssetTriggerHandler.afterUpdate: line 109 column 1 Trigger.AssetTrigger: line 24 column 1 ]
2024-06-23 12:33:48 [Mapping_Vehicle_Asset] Failed to save record [ID=02i1Q000008dnp5QAA Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:AssetTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.CreateTasksAndCasesOnDeliveryForEU.createTasksOnDeliveryFromAsset: line 202 column 1 Class.AssetTriggerHandler.createTasksOnDeliveryForEU: line 393 column 1 Class.AssetTriggerHandler.afterUpdate: line 109 column 1 Trigger.AssetTrigger: line 24 column 1 ]
2024-06-24 16:22:34 [Mapping_Vehicle_Asset] Failed to save record [ID=02i1Q000008dnpRQAQ Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:AssetTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.CreateTasksAndCasesOnDeliveryForEU.createTasksOnDeliveryFromAsset: line 202 column 1 Class.AssetTriggerHandler.createTasksOnDeliveryForEU: line 393 column 1 Class.AssetTriggerHandler.afterUpdate: line 109 column 1 Trigger.AssetTrigger: line 24 column 1 ]
2024-06-25 09:11:19 [Mapping_Vehicle_Asset] Failed to save record [ID=02i1Q000008dnq2QAA Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:AssetTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.CreateTasksAndCasesOnDeliveryForEU.createTasksOnDeliveryFromAsset: line 20
2024-06-26 14:00:05 [Mapping_VehicleSalesOrder_Delivery] 1 of 35 records failed to save.[Mapping_VehicleSalesOrder_Delivery] Failed to save record [ID=a0JHp00000m4WQNMA2 Message=FIELD_CUSTOM_VALIDATION_EXCEPTION:You may not modify an Order or Delivery's VIN assignment after a delivery has occurred ]
2024-06-27 08:48:50 [Mapping_VehicleSalesOrder_Delivery] Failed to save record [ID=a0J1Q00000jSu5LUAS Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:DeliveryTrigger: execution of BeforeUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 8011Q00000JmxHCQAZ; first error: DUPLICATE_VALUE duplicate value found: Unique_Vehicle_Id__c duplicates value on record with id: 801Hp00000OxhBgIAJ: [] Class.DeliveryTriggerHandler.updateOrderAsset: line 276 column 1 Class.DeliveryTriggerHandler.runTrigger: line 43 column 1 Trigger.DeliveryTrigger: line 17 column 1 ]
2024-06-28 11:37:36 [Mapping_VehicleSalesOrder_Delivery] Failed to save record [ID=a0J1Q00000l0q0RUAQ Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:DeliveryTrigger: execution of BeforeUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 8011Q00000JmxHCQAZ; first error: DUPLICATE_VALUE duplicate value found: Unique_Vehicle_Id__c duplicates value on record with id: 801Hp00000OxhBgIAJ: [] Class.DeliveryTriggerHandler.updateOrderAsset: line 276 column 1 Class.DeliveryTriggerHandler.runTrigger: line 43 column 1 Trigger.DeliveryTrigger: line 17 column 1 ]
2024-06-29 15:26:21 [Mapping_VehicleSalesOrder_Delivery] Failed to save record [ID=a0J1Q00000l078vUAA Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:DeliveryTrigger: execution of BeforeUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 8011Q00000JmxHCQAZ; first error: DUPLICATE_VALUE duplicate value found: Unique_Vehicle_Id__c duplicates value on record with id: 801Hp00000OxhBgIAJ: [] Class.DeliveryTriggerHandler.updateOrderAsset: line 276 column 1 Class.DeliveryTriggerHandler.runTrigger: line 43 column 1 Trigger.DeliveryTrigger: line 17 column 1 ]
2024-06-30 07:15:07 [Mapping_VehicleSalesOrder_Delivery] Failed to save record [ID=a0J1Q00000lUoYQUA0 Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:DeliveryTrigger: execution of BeforeUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 8011Q00000JmxHCQAZ; first error: DUPLICATE_VALUE duplicate value found: Unique_Vehicle_Id__c duplicates value on record with id: 801Hp00000OxhBgIAJ: [] Class.DeliveryTriggerHandler.updateOrderAsset: line 276 column 1 Class.DeliveryTriggerHandler.runTrigger: line 43 column 1 Trigger.DeliveryTrigger: line 17 column 1 ]
2024-07-01 10:03:52 [Mapping_VehicleSalesOrder_Delivery] Failed to save record [ID=a0J1Q00000lmYZWUA2 Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:DeliveryTrigger: execution of BeforeUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 8011Q00000JmxHCQAZ; first error: DUPLICATE_VALUE duplicate value found: Unique_Vehicle_Id__c duplicates value on record with id: 801Hp00000OxhBgIAJ: [] Class.DeliveryTriggerHandler.updateOrderAsset: line 276 column 1 Class.DeliveryTriggerHandler.runTrigger: line 43 column 1 Trigger.DeliveryTrigger: line 17 column 1 ]
2024-07-02 13:52:38 [Mapping_VehicleSalesOrder_Delivery] Failed to save record [ID=a0J1Q00000io5RqUAI Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:DeliveryTrigger: execution of BeforeUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 8011Q00000JmxHCQAZ; first error: DUPLICATE_VALUE duplicate value found: Unique_Vehicle_Id__c duplicates value on record with id: 801Hp00000OxhBgIAJ: [] Class.DeliveryTriggerHandler.updateOrderAsset: line 276 column 1 Class.DeliveryTriggerHandler.runTrigger: line 43 column 1 Trigger.DeliveryTrigger: line 17 column 1 ]
2024-07-03 16:41:23 [Mapping_VehicleSalesOrder_Delivery] Failed to save record [ID=a0JHp00000m4qN4MAI Message=CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:DeliveryTrigger: execution of BeforeUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 8011Q00000JmxHCQAZ; first error: DUPLICATE_VALUE duplicate value found: Unique_Vehicle_Id__c duplicates value on record with id: 801Hp00000OxhBgIAJ: [] Class.DeliveryTriggerHandler.updateOrderAsset: line 276 column 1 Class.DeliveryTriggerHandler.runTrigger: line 43 column 1 Trigger.DeliveryTrigger: line 17 column 1 ]
2024-07-04 08:30:09 [Mapping_VehicleSalesOrd
2024-07-05 11:18:54 [MappingExecutionBatch] Failed to start mapping [Vehicle_Asset]. overcast.DMLManager.PermissionDeniedException: This user does not have permission to read lucVMSVehicleRep_ZVMS_A_VMSVEHICLE__c.ConfigurationNumber__c.
2024-07-06 15:07:40 Acknowledgment timeout error. Overcast service did not connect back to Salesforce in a timely manner. Check that the Salesforce Job Connection String is valid.
2024-07-07 07:56:25 Call to OData source failed. HTTP error code="414" message="URI Too Long"
2024-07-08 10:45:11 Call to OData source failed. HTTP error code="503" message="Service Unavailable"OC-ODT-200 Web Service returned an error. (u1BdzDrQ) ---> HTTP error code="503" message="Service Unavailable". No additional OData error message available.
2024-07-09 13:33:56 e or established connection failed because connected host has failed to respond 10.171.33.135:443OC-ODT-225 Connection failure encountered. (u1dgx2cG) ---> An error occurred while sending the request. ---> Unable to connect to the remote server ---> A connection attempt failed because the connected party did not properly respond after a period of tim
2024-07-10 16:22:42 Execution terminated manually.
2024-07-11 08:11:27 Scenario execution timed out and was terminated.
2024-07-12 11:00:13 StackTrace: (overcast)Line 182 System.CalloutException: IO Exception: Connection reset
2024-07-13 13:48:58 This scenario is already in process. This run will be terminated.
2024-07-14 07:37:44 [MappingExecution] You've exceeded the limit of 100 jobs in the flex queue for org 00D36000000p5Xr. Wait for some of your batch jobs to finish before adding more. To monitor and reorder jobs, use the Apex Flex Queue page in Setup.
2024-07-15 10:26:29 [MappingExecutionBatch] Apex Class [Mapping_LIKP_Delivery] threw an unhandled exception: System.QueryException: Record Currently Unavailable: The record you are attempting to edit or one of its related records is currently being modified by another user. Please try again.
2024-07-16 13:15:15 Acknowledgment timeout error. Overcast service did not connect back to Salesforce in a timely manner. Check that the Salesforce Job Connection String is valid.
2024-07-17 16:04:00 OC-SAP-002 Request timed out. (u26wdr3l)
2024-07-18 08:52:46 OC-SAP-211 SAP returned an error. (u2PiQB0K) ---> ERROR partner '10.171.33.64:3601' not reached TIME Mon Oct 23 17:00:38 2023 RELEASE 785 COMPONENT NI (network interface) VERSION 40 RC -10 MODULE D:/depot/bas/785_REL/src/base/ni/nixxi.cpp LINE 3502 DETAIL NiPConnect2: 10.171.33.64:3601 SYSTEM CALL connect ERRNO 10060 ERRNO TEXT WSAETIMEDOUT: Connection timed out COUNTER 2 RETURN CODE: -101
2024-07-19 11:41:31 Scenario execution timed out and was terminated.
2024-07-20 14:30:17 src/base/ni/nixxi.cpp LINE 3502 DETAIL NiPConnect2: 10.171.33.64:3601 SYSTEM CALL connect ERRNO 10061 ERRNO TEXT WSAECONNREFUSED: Connection refused COUNTER 3 RETURN CODE: -101OC-SAP-211 SAP returned an error. (u1O325BS) ---> ERROR partner '10.171.33.64:3601' not reached TIME Sun Dec 10 11:00:09 2023 RELEASE 785 COMPONENT NI (network interface) VERSION 40 RC -10 MODULE D:/depot/bas/785_REL/
2024-07-21 07:19:02 This scenario is already in process. This run will be terminated.
2024-07-22 10:07:48 [ActionRunInboundMapping] Failed to start mapping [DeliveryHeader_Delivery]. overcast.DMLManager.PermissionDeniedException: This user does not have permission to read ovcS4OutboundDeliveryDS_AOutbDeliveryHea__c.ovcTimestamp__c.
2024-07-23 12:56:33 Acknowledgment timeout error. Overcast service did not connect back to Salesforce in a timely manner. Check that the Salesforce Job Connection String is valid.
2024-07-24 15:45:19 Call to OData source failed. HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed."OC-ODT-200 Web Service returned an error. (u1EFjWLZ ) ---> HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed.". No additional OData error message available.
2024-07-25 08:34:04 Call to OData source failed. HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed."OC-ODT-200 Web Service returned an error. (u2wqfr3x) --- HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed.". No additional OData error message available.
2024-07-26 11:22:50 Call to OData source failed. HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed."OC-ODT-200 Web Service returned an error. (u2XeSt4q) ---> HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed.". No additional OData error message available.
2024-07-27 14:11:35 Call to OData source failed. HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed."OC-ODT-200 Web Service returned an error. (u2yQrECC) ---> HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed.". No additional OData error message available.
2024-07-28 07:00:21 Delivery items could not be created (see log)
2024-07-29 09:49:06 Error while updating delivery 80009419
2024-07-30 12:37:52 Error while updating delivery 80009449
2024-07-31 15:26:37 Error while updating delivery 80009797
2024-08-01 08:15:23 Error while updating delivery 80009806
2024-06-15 11:04:08 Error while updating delivery 80010004
2024-06-16 13:52:54 Error while updating delivery 80010021
2024-06-17 16:41:39 Error while updating delivery 
2024-06-18 09:30:25 Goods issue has already been posted for delivery
2024-06-19 12:19:10 Delivery items could not be created (see log)
2024-06-20 15:07:56 No authorization to create deliveries for shipping point 1012
2024-06-21 07:56:41 OC-ODT-200 Web Service returned an error. (u2tb76S1) ---> HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed.". No additional OData error message available.Call to OData source failed. HTTP error code="403" message="Request failed with reason 403 Forbidden. Response content was CSRF token validation failed."
2024-06-22 10:45:27 OC-ODT-225 Connection failure encountered. (u2vHwNNP) ---> An error occurred while sending the request. ---> Unable to connect to the remote server ---> A connection attempt failed because the connected party did not properly respond after a period of time or established connection failed because connected host has failed to respond 10.171.33.135:443
2024-06-23 13:34:12 Resource not found for segment 'A_OutbDeliveryHeaderType'
2024-06-24 16:22:58 The sales order 30041336 is currently being processed by user TRACYGIBSON 
2024-06-25 08:11:44 Read timed outRead timed outRead timed out
2024-06-26 11:00:30 Enter a value for field Last name of business partner (person)
2024-06-27 13:49:15 Do not use gaps in postal code Palm Beach
2024-06-28 16:37:01 Postal code 2132BG must have the length 7
2024-06-29 09:25:46 Region RI is not defined for SA.
2024-06-30 12:14:32 [Mapping_Contact_BPAddress] Failed to save record [ID=null Message=STRING_TOO_LONG:StreetName: data value too large: Talha Bin Al Bara Unit 303 Riyah - Olaya Al-Qassim Region 12243 (max length=60) StreetName__c=Talha Bin Al Bara Unit 303 Riyah - Olaya Al-Qassim Region 12243][Mapping_Contact_BPAddress] 1 of 1 records failed to save.
2024-07-01 15:03:17 e or established connection failed because connected host has failed to respond 10.171.33.135:443OC-ODT-225 Connection failure encountered. (u1Eur76W) ---> An error occurred while sending the request. ---> Unable to connect to the remote server ---> A connection attempt failed because the connected party did not properly respond after a period of tim
2024-07-02 07:52:03 Call to OData source failed. HTTP error code="500" message="Request failed with reason 500 Internal Server Error. Response content was {"error":{"code":"/IWFND/CM_BEC/030" "message":{"lang":"en" "value":"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details"} "innererror":{"application":{"component_id":"LO-MD-BP" "service_namespace":"/SAP/" "service_id":"API_BUSINESS_PARTNER" "service_version":"0001"} "transactionid":"47A9734E1D0E01F0E0065757A0F2C3AD" "timestamp":"20231210100045.1401970" "Error_Resolution":{"SAP_Transaction":"For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details" "SAP_Note":"See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)"} "errordetails":[]}}}."Code:"/IWFND/CM_BEC/030" Message:"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details"Data source specific error: { "application": { "component_id": "LO-MD-BP" "service_namespace": "/SAP/" "service_id": "API_BUSINESS_PARTNER" "service_version": "0001" } "transactionid": "47A9734E1D0E01F0E0065757A0F2C3AD" "timestamp": "20231210100045.1401970" "Error_Resolution": { "SAP_Transaction": "For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries withthe timestamp above for more details" "SAP_Note": "See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }OC-ODT-201 Web Service returned an error. (u1pYjmVG) ---> Code:"/IWFND/CM_BEC/030" Message:"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details" ---> { "application": { "component_id": "LO-MD-BP" "service_namespace": "/SAP/" "service_id": "API_BUSINESS_PARTNER" "service_version": "0001" } "transactionid": "47A9734E1D0E01F0E0065757A0F2C3AD" "timestamp": "20231210100045.1401970" "Error_Resolution": { "SAP_Transaction": "For backendadministrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details" "SAP_Note": "See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }
2024-07-03 10:40:48 administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details" "SAP_Note": "See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }Call to OData source failed. HTTP error code="500" message="Request failed with reason 500 Internal Server Error. Response content was {"error":{"code":"/IWFND/CM_BEC/030" "message":{"lang":"en" "value":"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details"} "innererror":{"application":{"component_id":"LO-MD-BP" "service_namespace":"/SAP/" "service_id":"API_BUSINESS_PARTNER" "service_version":"0001"} "transactionid":"47A9734E1D0E0390E0065753DB96A51A" "timestamp":"20231210094505.4825010" "Error_Resolution":{"SAP_Transaction":"For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details" "SAP_Note":"See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)"} "errordetails":[]}}}."Code:"/IWFND/CM_BEC/030" Message:"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details"Data source specific error: { "application": { "component_id": "LO-MD-BP" "service_namespace": "/SAP/" "service_id": "API_BUSINESS_PARTNER" "service_version": "0001" } "transactionid": "47A9734E1D0E0390E0065753DB96A51A" "timestamp": "20231210094505.4825010" "Error_Resolution": { "SAP_Transaction": "For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries withthe timestamp above for more details" "SAP_Note": "See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }OC-ODT-201 Web Service returned an error. (u19ow59X) ---> Code:"/IWFND/CM_BEC/030" Message:"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details" ---> { "application": { "component_id": "LO-MD-BP" "service_namespace": "/SAP/" "service_id": "API_BUSINESS_PARTNER" "service_version": "0001" } "transactionid": "47A9734E1D0E0390E0065753DB96A51A" "timestamp": "20231210094505.4825010" "Error_Resolution": { "SAP_Transaction": "For backend
2024-07-04 13:29:34 ://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }Call to OData source failed. HTTP error code="500" message="Request failed with reason 500 Internal Server Error. Response content was {"error":{"code":"/IWFND/CM_BEC/030" "message":{"lang":"en" "value":"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details"} "innererror":{"application":{"component_id":"LO-MD-BP" "service_namespace":"/SAP/" "service_id":"API_BUSINESS_PARTNER" "service_version":"0001"} "transactionid":"47A9734E1D0E0390E0065753DB96A51C" "timestamp":"20231210094506.6280250" "Error_Resolution":{"SAP_Transaction":"For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details" "SAP_Note":"See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)"} "errordetails":[]}}}."Code:"/IWFND/CM_BEC/030" Message:"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details"Data source specific error: { "application": { "component_id": "LO-MD-BP" "service_namespace": "/SAP/" "service_id": "API_BUSINESS_PARTNER" "service_version": "0001" } "transactionid": "47A9734E1D0E0390E0065753DB96A51C" "timestamp": "20231210094506.6280250" "Error_Resolution": { "SAP_Transaction": "For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries withthe timestamp above for more details" "SAP_Note": "See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }OC-ODT-201 Web Service returned an error. (u2qZpXjQ) ---> Code:"/IWFND/CM_BEC/030" Message:"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details" ---> { "application": { "component_id": "LO-MD-BP" "service_namespace": "/SAP/" "service_id": "API_BUSINESS_PARTNER" "service_version": "0001" } "transactionid": "47A9734E1D0E0390E0065753DB96A51C" "timestamp": "20231210094506.6280250" "Error_Resolution": { "SAP_Transaction": "For backendadministrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details" "SAP_Note": "See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }
2024-07-05 16:18:20 A task was canceled.OC-ODT-002 Request timed out. (u1giAI7W)
2024-07-06 08:07:05 [Contact_BP] SObject row was retrieved via SOQL without querying the requested field: Contact.ovcLanguage__c
2024-07-07 10:55:51 [ActionRunInboundMapping] Apex Class [Mapping_BPResult_Contact] threw an unhandled exception: System.QueryException: Record Currently Unavailable: The record you are attempting to edit or one of its related records is currently being modified by anotheruser. Please try again.
2024-07-08 13:44:36 Resource not found for segment 'A_CustomerCompanyType'
2024-07-09 16:33:22 [ActionRunInboundMapping] Apex Class [Mapping_BPResult_Contact] threw a DML exception: System.DmlException: Update failed. First exception on row 0 with id 001Hp00002c4hv7IAA; first error: UNABLE_TO_LOCK_ROW unable to obtain exclusive access to this record or 1 records: 001Hp00002c4hv7IAA: []
2024-07-10 09:22:07 ation DEV_RFC for more details"} "innererror":{"application":{"component_id":"LO-MD-BP" "service_namespace":"/SAP/" "service_id":"API_BUSINESS_PARTNER" "service_version":"0001"} "transactionid":"47A9734E1D0E0390E0065753DB96A636" "timestamp":"20231210101511.0704470" "Error_Resolution":{"SAP_Transaction":"For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details" "SACall to OData source failed. HTTP error code="500" message="Request failed with reason 500 Internal Server Error. Response content was {"error":{"code":"/IWFND/CM_BEC/030" "message":{"lang":"en" "value":"RFC Error: Run 'Connection Test' in sm59 for destinace": "/SAP/" "service_id": "API_BUSINESS_PARTNER" "service_version": "0001" } "transactionid": "47A9734E1D0E0390E0065753DB96A636" "timestamp": "20231210101511.0704470" "Error_Resolution": { "SAP_Transaction": "For backendadministrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details" "SAP_Note": "See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }OC-ODT-201 Web Service returned an error. (u2wQehPB) ---> Code:"/IWFND/CM_BEC/030" Message:"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details" ---> { "application": { "component_id": "LO-MD-BP" "service_namespace": "/SAP/" "service_id": "API_BUSINESS_PARTNER" "service_version": "0001" } "transactionid": "47A9734E1D0E0390E0065753DB96A636" "timestamp": "20231210101511.0704470" "Error_Resolution": { "SAP_Transaction": "For backendadministrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries withthe timestamp above for more details" "SAP_Note": "See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }P_Note":"See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)"} "errordetails":[]}}}."Code:"/IWFND/CM_BEC/030" Message:"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details"Data source specific error: { "application": { "component_id": "LO-MD-BP" "service_namespace": "/SAP/" "service_id": "API_BUSINESS_PARTNER" "service_version": "0001" } "transactionid": "47A9734E1D0E0390E0065753DB96A636" "timestamp": "20231210101511.0704470" "Error_Resolution": { "SAP_Transaction": "For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries withthe timestamp above for more details" "SAP_Note": "See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)" } "errordetails": [] }OC-ODT-201 Web Service returned an error. (u2wQehPB) ---> Code:"/IWFND/CM_BEC/030" Message:"RFC Error: Run 'Connection Test' in sm59 for destination DEV_RFC for more details" ---> { "application": { "component_id": "LO-MD-BP" "service_namespace": "
